### ISSUE TITLE
Popup message is below content

### ISSUE THREAD

**Issue by hodovani** [vrizo/uibook#1] opened 2019-03-19 19:50 UTC
I found that popup is below the header.

![image](https://user-images.githubusercontent.com/12833067/54637249-db823380-4a90-11e9-8ed6-7f3daaee8caf.png)

**Comment by vrizo** [comment] 2019-03-20 10:09
Thanks for the bug report, @hodovani ! I'm going to increase z-index for Uibook elements.

**Comment by vrizo** [comment] 2019-04-14 08:18
Fixed in https://github.com/vrizo/uibook/commit/db80746b4cbdf66907088cf96686a81fa5d230b7

Top layer has a larger `z-index` value than Case container now. Anyway it can't fix overlapping due to Custom Wrappers, but that's not a bug, we can't consider all possible wrappers.

**Closed by vrizo** 2019-04-14 08:18 UTC
Labels: bug
